tram_admin:
    resource: "@TramAdminBundle/Resources/config/routing.yml"
    prefix:   /

tram_user:
    resource: "@TramUserBundle/Resources/config/routing.yml"
    prefix:   /
tram:
    resource: "@TramBundle/Resources/config/routing.yml"
    prefix:   /
root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /Lignes
        permanent: true
