security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/admin/login$
            security: true
            anonymous: true
            context: admin
        admin:
            pattern:   ^/admin
            anonymous: false
            context: admin
            provider:  in_memory
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                always_use_default_target_path: false
                default_target_path: /admin/
            logout:
                path:   /admin/logout
                target: /

        main:
            pattern:   ^/
            anonymous: true

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
