<?php

namespace Tram\TramBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectionRepository extends EntityRepository
{
    


}
