<?php

namespace Tram\TramBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneRepository extends EntityRepository
{
  public function findAllLignes() {
    $qb = $this->createQueryBuilder('a');

    $qb->join('a.accidents', 'l')
       ->addSelect();

    $result = $qb
    ->getQuery()
    ->getResult()
    ;

    return $result;
  }
}
