tram_homepage:
    path:     /Lignes/
    defaults: { _controller: TramBundle:Ligne:index }
tram_ligne:
    path:     /Lignes/{code}/Stops
    defaults: { _controller: TramBundle:Ligne:ligne}
tram_stop:
    path:     /Lignes/{code_ligne}/Stops/{code_stop}
    defaults: { _controller: TramBundle:Ligne:stop}
agent_add:
    path:     /Agent/add/{stop}
    defaults: { _controller: TramBundle:Agent:addAgent }
agent_show:
    path:     /Agent/{stop}
    defaults: { _controller: TramBundle:Agent:showAgent }
