tram_homepage:
    path:     /Lignes/
    defaults: { _controller: TramBundle:Ligne:index }
tram_ligne:
    path:     /Lignes/{code}/Stops
    defaults: { _controller: TramBundle:Ligne:ligne}
tram_stop:
    path:     /Lignes/{code_ligne}/Stops/{code_stop}
    defaults: { _controller: TramBundle:Ligne:stop}

# API agent
agent_add:
    path:     /api/Agent/add/{stop}
    defaults: { _controller: TramBundle:Agent:addAgent }
agent_show:
    path:     /api/Agent/{stop}
    defaults: { _controller: TramBundle:Agent:showAgent }
 
# API ligne
tram_api_lignes:
    path:     /api/Lignes
    defaults: { _controller: TramBundle:API:index }
tram_api_stops:
    path:     /api/Lignes/{code}/Stops
    defaults: { _controller: TramBundle:API:ligne}
tram_api_stop:
    path:     /api/Lignes/{code_ligne}/Stops/{code_stop}
    defaults: { _controller: TramBundle:API:stop}
