index_admin:
    path:     /admin/
    defaults: { _controller: TramAdminBundle:Admin:index }
stat_admin:
    path:     /admin/stat
    defaults: { _controller: TramAdminBundle:Admin:stat }
log_admin:
    path:     /admin/log
    defaults: { _controller: TramAdminBundle:Admin:log }
